### ISSUE TITLE
[BUG]: POS Awesome Invalid Method

### ISSUE THREAD

**Issue by shuhain85** [yrestom/POS-Awesome#140]
Doko  v2.0.15 (master)
Dodock: v2.0.13 (master)
POS Awesome: v3.2.1 (master)

### Stacktrace / full error message
Traceback (most recent call last):
  File "/home/dokos/dokos-bench/apps/frappe/frappe/handler.py", line 55, in execute_cmd
    frappe.throw(_('Invalid Method'))
  File "/home/dokos/dokos-bench/apps/frappe/frappe/handler.py", line 188, in get_attr
    method = globals()[cmd]
  File "/home/dokos/dokos-bench/apps/frappe/frappe/__init__.py", line 1159, in get_attr
    def get_attr(method_string):
  File "/home/dokos/dokos-bench/apps/frappe/frappe/__init__.py", line 923, in get_module
    """
  File "/home/dokos/dokos-bench/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dokos/dokos-bench/apps/posawesome/posawesome/posawesome/api/posapp.py", line 16, in <module>
    from erpnext.accounts.doctype.payment_request.payment_request import (
ImportError: cannot import name 'get_dummy_message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dokos/dokos-bench/apps/frappe/frappe/app.py", line 67, in application
    elif request.path.startswith("/api/"):
  File "/home/dokos/dokos-bench/apps/frappe/frappe/api.py", line 58, in handle
    method = frappe.local.form_dict.pop("run_method")
  File "/home/dokos/dokos-bench/apps/frappe/frappe/handler.py", line 30, in handle
    # data can be an empty string or list which are valid responses
  File "/home/dokos/dokos-bench/apps/frappe/frappe/handler.py", line 57, in execute_cmd
    if from_async:
  File "/home/dokos/dokos-bench/apps/frappe/frappe/__init__.py", line 417, in throw
    if len(local.message_log) > 0:
  File "/home/dokos/dokos-bench/apps/frappe/frappe/__init__.py", line 396, in msgprint
    if wide:
  File "/home/dokos/dokos-bench/apps/frappe/frappe/__init__.py", line 350, in _raise_exception
frappe.exceptions.ValidationError: Invalid Method

### Steps to reproduce

Open POS Awseome

### Screenshots

![image](https://user-images.githubusercontent.com/85258348/160024397-f2f14e90-3318-4b95-adef-21a57f04b69d.png)

**Comment by yrestom** [comment]
The issue we are using this function from Erpnext: 
https://github.com/frappe/erpnext/blob/8e425252c413dc40bdbd07c567adf430bf8efe0e/erpnext/accounts/doctype/payment_request/payment_request.py#L593

And it seems it did not exist in Dodock
