### ISSUE TITLE
[BUG]: Error while trying to 'Use Customer Credit'

### ISSUE THREAD

**Issue by N1RMS** [yrestom/POS-Awesome#195]
"erpnext": "13.29.0",
"erpnext_shipping": "0.0.1",
"erpnext_telegram_integration": "1.0.1",
"frappe": "13.29.0",
"posawesome": "3.3.0"

The error im getting while trying to redeem customer credit:
Sales Order is mandatory for Item xxx
`
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1448, in call
    return fn(*args, **newargs)
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 467, in submit_invoice
    invoice_doc.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 347, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1052, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1260, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1242, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 100, in validate
    self.so_dn_required()
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 771, in so_dn_required
    msgprint(_("{0} is mandatory for Item {1}").format(key, d.item_code), raise_exception=1)
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 436, in _raise_exception
    raise ValidationError(msg)
frappe.exceptions.ValidationError: Sales Order is mandatory for Item 072512068656
`
console error^

**Comment by N1RMS** [comment]
Occurs because 'Is Sales Order Required for Sales Invoice & Delivery Note Creation?' is enabled
