### ISSUE TITLE
[BUG]: Error while edit customer info 

### ISSUE THREAD

**Issue by AlaaBadry** [yrestom/POS-Awesome#201]
### App Versions
```
{
	"chat": "0.0.1",
	"erpnext": "13.39.0",
	"frappe": "13.41.1",
	"lms": "0.0.1",
	"posawesome": "3.4.0"
}
```
### Route
```
posapp
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
TypeError: set_customer_info() missing 1 required positional argument: 'customer'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"fieldname": "mobile_no",
		"value": "+201211159151"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/posawesome.posawesome.api.posapp.set_customer_info"
}
```
### Response Data
```
{
	"exception": "TypeError: set_customer_info() missing 1 required positional argument: 'customer'"
}
![screenbud-307f36ba-bf41-46f2-9b40-2aba56f1449b](https://user-images.githubusercontent.com/26534497/192181065-3b4f031f-6714-4160-a595-f8526137df6a.png)

**Comment by AlaaBadry** [comment]
![image](https://user-images.githubusercontent.com/26534497/192180891-060b5ff7-e5f7-4e3c-a381-b584e9e32683.png)
