### ISSUE TITLE
[BUG]: An error occurred while installing posawesome: Item Barcode: Field Barcode in row 1 cannot be hidden and mandatory without default

### ISSUE THREAD

**Issue by ruggeromicheletti** [yrestom/POS-Awesome#206]
ERPNext: v13.39.2 (version-13)

Frappe Framework: v13.41.3 (version-13)

- POS Awesome: ](https://github.com/yrestom/POS-Awesome.git)

### Stacktrace / full error message

An error occurred while installing posawesome: Item Barcode: Field Barcode in row 1 cannot be hidden and mandatory without default
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 293, in install_app
    _install_app(app, verbose=context.verbose)
  File "apps/frappe/frappe/installer.py", line 199, in install_app
    sync_fixtures(name)
  File "apps/frappe/frappe/utils/fixtures.py", line 22, in sync_fixtures
    import_doc(fixtures_path)
  File "apps/frappe/frappe/core/doctype/data_import/data_import.py", line 180, in import_doc
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 146, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 275, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1085, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1243, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 88, in on_update
    validate_fields_for_doctype(self.dt)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 907, in validate_fields_for_doctype
    validate_fields(meta)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1312, in validate_fields
    check_hidden_and_mandatory(meta.get("name"), d)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1003, in check_hidden_and_mandatory
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.core.doctype.doctype.doctype.HiddenAndMandatoryWithoutDefaultError: Item Barcode: Field Barcode in row 1 cannot be hidden and mandatory without default

### What is actually happening?
error occurs while installing posawesome to my site

**Comment by olumobrian** [comment]
I also have the same issue. I think it is with the updated ERPNext. Also if I ignore this and continue to install, the referral code section does not appear when creating an new customer meaning I cannot save the customer because of the missing attribute. And maybe some other issues, didn't go past that

If they can update POS Awesome, I'd also highly appreciate
Thanks

**Comment by tedyswaga** [comment]
The only time I experienced this error I checked Show _**Barcode Field in Stock Transactions**_, in stock settings and the error disappeared.
