### ISSUE TITLE
[BUG]: Blank Screen

### ISSUE THREAD

**Issue by nitin-anantpranali** [yrestom/POS-Awesome#221]
Hi,
I have installed the app on my site and getting new options in the POS profiles.
But when I click on the POS Awesome POS shortcut, it shows blank screen.
What could be the issue?

### Versions
ERPNext: v14.x.x-develop () (develop)
Frappe Framework: v14.x.x-develop () (develop)
Payments: v0.0.1 (develop)
POS Awesome: v4.0.0 (version-14)

**Comment by yrestom** [comment]
did you run `bench build` ?

**Comment by nitin-anantpranali** [comment]
Yes I run bench build.
Still blank

**Comment by yrestom** [comment]
In browser console is there any errors?

**Comment by git-avc** [comment]
I think it's the same issue.
Loading POS Awesome app

Console:
`request.js:303 TypeError: Cannot read properties of undefined (reading 'posapp')
    at frappe.pages.posapp.on_page_load (posapp.js:9:40)
    at Page2.trigger_page_event (pageview.js:102:15)
    at new Page2 (pageview.js:89:8)
    at pageview.js:52:6
    at Object.callback (pageview.js:36:6)
    at Object.callback [as success_callback] (request.js:85:16)
    at 200 (request.js:128:34)
    at Object.<anonymous> (request.js:299:6)
    at fire (jquery.js:3500:31)
    at Object.fireWith [as resolveWith] (jquery.js:3630:7)`

**Comment by yrestom** [comment]
@git-avc What POS version are you using?

**Comment by yrestom** [comment]
Try `bench setup requirements`

**Comment by azharrahman021** [comment]
> 

Even I'm facing this error and issue .bench setup requirements dint help @yrestom

**Comment by yrestom** [comment]
@git-avc are you using branch `version-14` for POS Awesome?

**Comment by git-avc** [comment]
Hi! I was using `develop` branch.  I will try with version-14 and confirm if is working!
Thanks @yrestom

**Comment by git-avc** [comment]
frappe + erpnext + posawesome is working for me with `version-14`

**Comment by umindo** [comment]
I have same problem and follow this link https://webpack.js.org/loaders/source-map-loader/
and problem solved. Try it

**Comment by yrestom** [comment]
> I have same problem and follow this link https://webpack.js.org/loaders/source-map-loader/
> and problem solved. Try it

Can you explain more?

**Comment by skanel** [comment]
I have the same issue.

**Comment by yasinelabe** [comment]
Anyone fixed this issue yet ?
