### ISSUE TITLE
[BUG]: `Payment Entry is already created` error, for Mpesa Express payment.

### ISSUE THREAD

**Issue by Lucky-Tsuma** [yrestom/POS-Awesome#257]
### Versions

- Frappe: V14.26.3
- Erpnext: V14.17.4
- POS Awesome: V4.1.1

### Stacktrace / full error message

```
14:57:45 web.1            |   val = self.func(instance)
14:57:45 web.1            | Traceback (most recent call last):
14:57:45 web.1            |   File "apps/frappe/frappe/app.py", line 66, in application
14:57:45 web.1            |     response = frappe.api.handle()
14:57:45 web.1            |   File "apps/frappe/frappe/api.py", line 54, in handle
14:57:45 web.1            |     return frappe.handler.handle()
14:57:45 web.1            |   File "apps/frappe/frappe/handler.py", line 45, in handle
14:57:45 web.1            |     data = execute_cmd(cmd)
14:57:45 web.1            |   File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
14:57:45 web.1            |     return frappe.call(method, **frappe.form_dict)
14:57:45 web.1            |   File "apps/frappe/frappe/_init_.py", line 1607, in call
14:57:45 web.1            |     return fn(*args, **newargs)
14:57:45 web.1            |   File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1217, in create_payment_request
14:57:45 web.1            |     pay_req = get_new_payment_request(doc, pay)
14:57:45 web.1            |   File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1245, in get_new_payment_request
14:57:45 web.1            |     return make_payment_request(**args)
14:57:45 web.1            |   File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1360, in make_payment_request
14:57:45 web.1            |     pr.insert(ignore_permissions=True)
14:57:45 web.1            |   File "apps/frappe/frappe/model/document.py", line 259, in insert
14:57:45 web.1            |     self.run_before_save_methods()
14:57:45 web.1            |   File "apps/frappe/frappe/model/document.py", line 1040, in run_before_save_methods
14:57:45 web.1            |     self.run_method("validate")
14:57:45 web.1            |   File "apps/frappe/frappe/model/document.py", line 909, in run_method
14:57:45 web.1            |     out = Document.hook(fn)(self, *args, **kwargs)
14:57:45 web.1            |   File "apps/frappe/frappe/model/document.py", line 1259, in composer
14:57:45 web.1            |     return composed(self, method, *args, **kwargs)
14:57:45 web.1            |   File "apps/frappe/frappe/model/document.py", line 1241, in runner
14:57:45 web.1            |     add_to_return_value(self, fn(self, *args, **kwargs))
14:57:45 web.1            |   File "apps/frappe/frappe/model/document.py", line 906, in fn
14:57:45 web.1            |     return method_object(*args, **kwargs)
14:57:45 web.1            |   File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 39, in validate
14:57:45 web.1            |     self.validate_payment_request_amount()
14:57:45 web.1            |   File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 54, in validate_payment_request_amount
14:57:45 web.1            |     ref_amount = get_amount(ref_doc, self.payment_account)
14:57:45 web.1            |   File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 519, in get_amount
14:57:45 web.1            |     frappe.throw(_("Payment Entry is already created"))
14:57:45 web.1            |   File "apps/frappe/frappe/_init_.py", line 525, in throw
14:57:45 web.1            |     msgprint(
14:57:45 web.1            |   File "apps/frappe/frappe/_init_.py", line 493, in msgprint
14:57:45 web.1            |     _raise_exception()
14:57:45 web.1            |   File "apps/frappe/frappe/_init_.py", line 442, in _raise_exception
14:57:45 web.1            |     raise raise_exception(msg)
14:57:45 web.1            | frappe.exceptions.ValidationError: Payment Entry is already created
```

### Steps to reproduce

1.  Set up mpesa settings on erpnext.
![mpesa settings](https://user-images.githubusercontent.com/55623011/222904372-bc419732-aee3-4920-8b38-aeee4ead3a02.jpeg)

2.Add mpesa express as mode of payment to your pos profile
![profile masked](https://user-images.githubusercontent.com/55623011/222913888-9ea53f5c-c7fe-494d-a4e9-ef85c5cc6f61.jpeg)

3. Make payment on posawesome, selecting Mpesa as mode of payment.
![tobepaid](https://user-images.githubusercontent.com/55623011/222904459-0edf114f-cd18-4564-921b-581586a96394.jpeg)

4. Enter phone number and hit 'request'
![phone](https://user-images.githubusercontent.com/55623011/222904486-a95b8edb-6668-473e-8a22-a7247beb9d54.jpeg)

5. See error
![error](https://user-images.githubusercontent.com/55623011/222904518-c98f7340-d430-4765-8605-35c8606fb99a.jpeg)

We expect to get an STK push notification on the phone number entered at step 4, but error pops ups as seen on step 5.

### Hint
Wrong value (Zero) for 'outstanding_amount' gets passed as error is seen to originate from:
apps/erpnext/erpnext/accounts/doctype/payment_request.py/get_amount
![code](https://user-images.githubusercontent.com/55623011/222904722-5e9bc1fb-b9bc-428f-92c7-2ce74a3ccdc0.jpeg)

One cannot edit the field labled 'To be Paid' on POSawesome.

**Comment by yrestom** [comment]
[fix: get mpesa account](https://github.com/yrestom/POS-Awesome/commit/1b5c17f61cf53948a36616d7ba3cbf288a58d2cc)
