### ISSUE TITLE
[BUG]: Payment Entry is already created on Sending Request for Mpesa Express

### ISSUE THREAD

**Issue by muchai** [yrestom/POS-Awesome#281]
### Versions

ERPNext: v14.19.0 (HEAD)
Frappe Framework: v14.29.0 (HEAD)
POS Awesome: v4.2.0 (HEAD)

### Stacktrace / full error message
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1219, in create_payment_request
    pay_req = get_new_payment_request(doc, pay)
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1247, in get_new_payment_request
    return make_payment_request(**args)
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1373, in make_payment_request
    pr.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 39, in validate
    self.validate_payment_request_amount()
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 54, in validate_payment_request_amount
    ref_amount = get_amount(ref_doc, self.payment_account)
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 515, in get_amount
    frappe.throw(_("Payment Entry is already created"))
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Payment Entry is already created

### Steps to reproduce

1. POS Awesome
2. Pick Customer, and Item to sell, then click Pay, then Send Mpesa Request to Customer Phone Number
3. Payment Entry is already created.

### What is Expected?
STK Push on customer phone, for them to accept or reject payment request.

### Additional context

- It sent first time, but subsequent requests raise this error. In this cases, it raised, items do not exist for invoice, after clicking permanently submit this invoice.
- Works on std POS.

### Screenshots
![image](https://user-images.githubusercontent.com/1822868/227442483-0e730f1e-25a6-4837-95fb-1f1cea1ea45d.png)

**Comment by yrestom** [comment]
It was fixed here [fix: get mpesa account](https://github.com/yrestom/POS-Awesome/commit/1b5c17f61cf53948a36616d7ba3cbf288a58d2cc)

**Comment by muchai** [comment]
Please check on this. We're on this latest version. This error happens minute there's already any other payment request. Work for the first case(no existing payment request)
