### ISSUE TITLE
[BUG]: Error during resending a failed, or rejected mpesa request for payment

### ISSUE THREAD

**Issue by muchai** [yrestom/POS-Awesome#291]
In some cases, when a mpesa express request is sent from the POS. The user may reject, intentionally, or most likely by accident.
In such a scenario, it should be possible to resend the request once more.

### Versions

Frappe Framework: v14.31.0 (HEAD)
ERPNext: v14.20.1 (HEAD)
POS Awesome: v4.2.2 (HEAD)

### Stacktrace / full error message
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1247, in create_payment_request
    pay_req.request_phone_payment()
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 133, in request_phone_payment
    controller.request_for_payment(**payment_record)
  File "apps/erpnext/erpnext/erpnext_integrations/doctype/mpesa_settings/mpesa_settings.py", line 65, in request_for_payment
    self.handle_api_response("CheckoutRequestID", args, response)
  File "apps/erpnext/erpnext/erpnext_integrations/doctype/mpesa_settings/mpesa_settings.py", line 119, in handle_api_response
    frappe.throw(_(getattr(response, "errorMessage")), title=_("Transaction Error"))
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Unable to lock subscriber, a transaction is already in process for the current subscriber

### Steps to reproduce

- Create a POS Sale
- Send a request to customer to pay
- Have the customer reject it, or it may fail for some reason
- Resend the request

### What is Expected?
A resending of the already created payment request, which is in requested status as of now.

### What is actually happening?
On resending, we get below error.
![image](https://user-images.githubusercontent.com/1822868/230182149-f2ef4cec-b08e-4175-bd18-bfb29d18ea00.png)

### Additional context
Works on std POS.

**Comment by yrestom** [comment]
I am unable to reproduce the problem

**Comment by muchai** [comment]
The payment request has to be in status Requested, i.e. Mpesa has already returned a non success message. The non success message could be due to the user cancelling the request(mostly by accident), or they didn't accept request because they were on another call.

**Comment by muchai** [comment]
Working.
