### ISSUE TITLE
[BUG]: (Offers) TypeError: '<' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by gitstephanferriggi** [yrestom/POS-Awesome#297]
- Erpnext: 
- POS Awesome: 

### App Versions
```
{
	"erpnext": "14.20.3",
	"frappe": "14.31.0",
	"hrms": "14.2.1",
	"payments": "0.0.1",
	"posawesome": "4.2.2"
}
```
### Route
```
posapp
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 354, in update_invoice
    invoice_doc.set_missing_values()
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 488, in set_missing_values
    super(SalesInvoice, self).set_missing_values(for_validate)
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 51, in set_missing_values
    self.set_price_list_and_item_details(for_validate=for_validate)
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 110, in set_price_list_and_item_details
    self.set_missing_item_details(for_validate=for_validate)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 595, in set_missing_item_details
    self.apply_pricing_rule_on_items(item, ret)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 649, in apply_pricing_rule_on_items
    if item.get(field) < pricing_rule_doc.get(field):
TypeError: '<' not supported between instances of 'str' and 'float'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"data": "{\"doctype\":\"Sales Invoice\",\"is_pos\":1,\"ignore_pricing_rule\":1,\"company\":\"Blooming Garden Ltd\",\"pos_profile\":\"Siggiewi Shop\",\"currency\":\"EUR\",\"customer\":\"CUST-2023-04742\",\"items\":[{\"item_code\":\"STO-ITEM-2023-02267\",\"posa_row_id\":\"7i8qytu6es2a3zdxzgrq\",\"posa_offers\":\"[\\\"hz9hv9a2tprzuwncw2yt\\\"]\",\"posa_offer_applied\":1,\"posa_is_offer\":0,\"posa_is_replace\":null,\"is_free_item\":0,\"qty\":1,\"rate\":0.5800000000000001,\"uom\":\"Ea\",\"amount\":0.5800000000000001,\"conversion_factor\":1,\"discount_percentage\":80,\"discount_amount\":\"2.32\",\"posa_notes\":\"\",\"posa_delivery_date\":\"\",\"price_list_rate\":2.9}],\"total\":\"0.58\",\"discount_amount\":0,\"additional_discount_percentage\":0,\"posa_pos_opening_shift\":\"POSA-OS-23-0000008\",\"payments\":[{\"amount\":0,\"mode_of_payment\":\"Cash\",\"default\":1,\"account\":\"\"},{\"amount\":0,\"mode_of_payment\":\"Cheque\",\"default\":0,\"account\":\"\"},{\"amount\":0,\"mode_of_payment\":\"Credit Card\",\"default\":0,\"account\":\"\"}],\"taxes\":[],\"posa_offers\":[{\"offer_name\":\"Buy 1 get 1 free\",\"row_id\":\"hz9hv9a2tprzuwncw2yt\",\"apply_on\":\"Item Code\",\"offer\":\"Item Price\",\"items\":\"[\\\"7i8qytu6es2a3zdxzgrq\\\"]\",\"offer_applied\":true,\"coupon_based\":0,\"coupon\":null}],\"posa_coupons\":[],\"posa_delivery_charges_rate\":0,\"posting_date\":\"2023-04-11\"}"
	},
	"headers": {},
	"error_handlers": {},
	"async": false,
	"url": "/api/method/posawesome.posawesome.api.posapp.update_invoice"
}
```
### Response Data
```
{
	"exception": "TypeError: '<' not supported between instances of 'str' and 'float'"
}
```

### Steps to reproduce

Create an offer on a product with discount %
Add product in POS awsome.
Press pay

### What is Expected?

The pay screen to open

### What is actually happening?

Error is coming up.

**Comment by gitstephanferriggi** [comment]
Thanks. It works.
