### ISSUE TITLE
[BUG]: Can't launch POS Awesome App with ERPnext V14

### ISSUE THREAD

**Issue by Nofal-Mami** [yrestom/POS-Awesome#307]
<!--  Thanks for your time to make POS Awesome better with your feedback 👍

**IMPORTANT** Before reporting a bug:

A properly detailed bug report can save a LOT of time and help fixing issues as soon as possible.
- ->

### Versions

Installed Apps

ERPNext: v14.11.0 (version-14)

Frappe Framework: v14.20.0 (version-14)

Payments: v0.0.1 (develop)

POS Awesome: v4.3.2 (version-14)

### Stacktrace / full error message

Traceback (most recent call last):
  File "apps/frappe/frappe/handler.py", line 72, in execute_cmd
    method = get_attr(cmd)
  File "apps/frappe/frappe/handler.py", line 258, in get_attr
    method = frappe.get_attr(cmd)
  File "apps/frappe/frappe/__init__.py", line 1580, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1322, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 29, in <module>
    from frappe.utils.caching import redis_cache
ImportError: cannot import name 'redis_cache' from 'frappe.utils.caching' (apps/frappe/frappe/utils/caching.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 74, in execute_cmd
    frappe.throw(_("Failed to get method for command {0} with {1}").format(cmd, e))
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Failed to get method for command posawesome.posawesome.api.posapp.check_opening_shift with cannot import name 'redis_cache' from 'frappe.utils.caching' 

### Steps to reproduce

1. Go to POS Awesome module
2. Click on POS Awesome App
3. See error message below
Failed to get method for command posawesome.posawesome.api.posapp.check_opening_shift with cannot import name 'redis_cache' from 'frappe.utils.caching' (/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py)

### What is Expected?
open POS Awesome and start selling

### What is actually happening?
Error message displayed, even no items showns nor customers

### Additional context
ERPNext installed as production mode.
POS profile created
Opening entry created
Fiscal year created
Item have stock and price

### Screenshots
![image](https://user-images.githubusercontent.com/35137381/236179375-4b96bbe0-41c3-40da-aea9-9b8dd096736f.png)

**Comment by yrestom** [comment]
POS Awesome V4.3.0 require Frappe V14.33.0 at least to work
It use a new feature in Frappe ["Redis cache decorator"](https://github.com/frappe/frappe/pull/20452) for speed up POS Awesome [feat: Use Redis cache](https://github.com/yrestom/POS-Awesome/commit/3235e9a40799844272aa74a8b3ea74f5d070f316) with an new option in POS Profile "Use Server Cache"

**Comment by Nofal-Mami** [comment]
Thanks Youssef for the prompt answer and support.

**Comment by Nofal-Mami** [comment]
It works perfect thx a lot
