### ISSUE TITLE
[BUG]: installation error v13

### ISSUE THREAD

**Issue by AlaaBadry** [yrestom/POS-Awesome#332]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

### What is actually happening?
Installing posawesome
$ /home/erpnext/bowandark/env/bin/python -m pip install --quiet --upgrade -e /home/erpnext/bowandark/apps/posawesome 
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/erpnext/bowandark/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/erpnext/bowandark/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/erpnext/bowandark/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-pncasg7r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-pncasg7r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-pncasg7r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-pncasg7r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-pncasg7r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "/home/erpnext/bowandark/apps/posawesome/posawesome/__init__.py", line 3, in <module>
          import frappe
      ModuleNotFoundError: No module named 'frappe'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: 
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/app.py", line 242, in install
    install_app(
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/app.py", line 573, in install_app
    bench.run(
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
INFO: A newer version of bench is available: 5.15.1 → 5.16.3

**Comment by yrestom** [comment]
Thank you for reporting this issue! To help us investigate and resolve it quickly, could you please provide the following information:

1. Versions:
   - Frappe: [e.g., V14.13.0]
   - Erpnext: [e.g., V14.14.0]
   - POS Awesome: [e.g., V6.1.0]

2. Stacktrace / Full error message:
   ```
   [Paste the error message or stacktrace here]
   ```

3. Steps to reproduce:
   Please provide detailed steps to reproduce the issue, such as:
   1. Go to '...'
   2. Click on '...'
   3. Scroll down to '...'
   4. See the error

4. Expected behavior:
   Describe what you expected to happen.

5. Actual behavior:
   Explain what is currently happening instead.

6. Additional context:
   If there is any additional information or context related to the problem, please share it here.

7. Screenshots:
   If applicable, you can also include screenshots to help us better understand the problem.

Your cooperation in providing these details will be highly appreciated. It will allow us to investigate and resolve the issue more effectively. Thank you!

**Comment by dawoodjee** [comment]
You've got to remove frappe and whatever is using it. I suspect the module isnt yet ready at this point

Quick workaround:

### Edit `./apps/posawesome/posawesome/__init__.py` as follows
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
#import frappe

__version__ = "6.0.4"


#def console(*data):
#    frappe.publish_realtime("toconsole", data, user=frappe.session.user)

```

### Restart bench
```bench restart```

### Then install posawesome manually

```./env/bin/python -m pip install --upgrade pip```

### Add `posawesome` to your `./sites/apps.txt`
```
frappe
erpnext
posawesome
```
