### ISSUE TITLE
[BUG]: sync POS profile (Event Streaming)

### ISSUE THREAD

**Issue by alsubaei** [yrestom/POS-Awesome#353]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```Traceback (most recent call last):
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 277, in sync
    set_insert(update, producer_site, event_producer.name)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 310, in set_insert
    sync_dependencies(doc, producer_site)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 492, in sync_dependencies
    dependency.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/account/account.py", line 48, in validate
    self.validate_root_details()
  File "apps/erpnext/erpnext/accounts/doctype/account/account.py", line 120, in validate_root_details
    frappe.throw(_("The root account {0} must be a group").format(frappe.bold(self.name)))
  File "apps/frappe/frappe/__init__.py", line 526, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 494, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 443, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: The root account <strong>Write Off - FC</strong> must be a group
```

### Steps to reproduce
https://docs.erpnext.com/docs/v13/user/manual/en/automation/event_streaming
follow this doc

### What is Expected?
status of creating the pos profile in the event sync log is synced

### What is actually happening?
status of creating the pos profile in the event sync log is failed

### Screenshots
If applicable, could you add screenshots to help explain your problem?
![image](https://github.com/yrestom/POS-Awesome/assets/76914152/f2e56fbd-d67f-482d-b03b-9c8fe6f68692)
![image](https://github.com/yrestom/POS-Awesome/assets/76914152/dbf0dc29-987d-4de1-8a9c-00c3de57c8d4)

**Comment by yrestom** [comment]
This issue is related to Erpnext Account doctype
Notice the error msg "The root account <strong>Write Off - FC</strong> must be a group"
