### ISSUE TITLE
[BUG]: "exception": "TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'"

### ISSUE THREAD

**Issue by muchai** [yrestom/POS-Awesome#388]
<!--  Thanks for your time to make POS Awesome better with your feedback 👍

**IMPORTANT** Before reporting a bug:

A properly detailed bug report can save a LOT of time and help fix issues as soon as possible.
- ->

### Versions

	"erpnext": "14.40.0",
	"frappe": "14.50.0",
	"posawesome": "6.1.3"

### Route

posapp

### Traceback

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/posawesome/posawesome/posawesome/api/payment_entry.py", line 364, in process_pos_payment
    reconcile_doc.reconcile()
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 398, in reconcile
    self.validate_allocation()
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 503, in validate_allocation
    if flt(row.allocated_amount) - invoice_outstanding > 0.009:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

### Request Data

{
	"type": "POST",
	"args": {
		"payload":
	},
	"freeze": true,
	"freeze_message": "Processing Payment",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/posawesome.posawesome.api.payment_entry.process_pos_payment"
}

### Response Data

{
"exception": "TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'"
}
has context menuParagraph

### Steps to reproduce

4. See the error

### Screenshots
If applicable, could you add screenshots to help explain your problem?

**Comment by yrestom** [comment]
@muchai How often this is happening?

**Comment by muchai** [comment]
Very rarely. Just one case so far.
