### ISSUE TITLE
Frappe installation error. "ValueError"

### ISSUE THREAD

**Issue by Machari-a** [yrestom/POS-Awesome#419]
After installing bench on Ubuntu 22.04.3 LTS as per the Frappe installation guideline, I keep getting an error when I run the bench start command

Traceback (most recent call last):
  File "/home/macharia/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/macharia/.local/lib/python3.10/site-packages/bench/cli.py", line 74, in cli
    cmd_from_sys = get_cmd_from_sysargv()
  File "/home/macharia/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 554, in get_cmd_from_sysargv
    if sys_argv.index(arg) == 0 and arg in Bench(".").apps:
  File "/home/macharia/.local/lib/python3.10/site-packages/bench/bench.py", line 67, in __init__
    self.apps = BenchApps(self)
  File "/home/macharia/.local/lib/python3.10/site-packages/bench/bench.py", line 175, in __init__
    self.initialize_apps()
  File "/home/macharia/.local/lib/python3.10/site-packages/bench/bench.py", line 282, in initialize_apps
    self.apps.remove("frappe")
ValueError: list.remove(x): x not in list

I have tried uninstalling and resinstalling the entire set up but still I have the same error. How do I resolve this?

**Comment by yrestom** [comment]
I am not sure about that error, I didn't see it before, you may ask it on the forum or on frappe Github
