### ISSUE TITLE
[BUG]: posawesome preventing from saving invocie after migration to erpnext15

### ISSUE THREAD

**Issue by multidoc** [yrestom/POS-Awesome#469]
<!--  Thanks for your time to make POS Awesome better with your feedback 👍

**IMPORTANT** Before reporting a bug:

A properly detailed bug report can save a LOT of time and help fix issues as soon as possible.
- ->Unable to save new invoices after migrating to erpnext15 and pos app not opening 

### Versions

ERPNext: v15.20.6 (version-15)

Frappe Framework: v15.23.0 (version-15)

Frappe HR: v16.0.0-dev (develop)

Payments: v0.0.1 (develop)

POS Awesome: v6.3.0 (develop)

### Stacktrace / full error message

```javascript
### App Versions
```
{
	"erpnext": "15.20.6",
	"frappe": "15.23.0",
	"hrms": "16.0.0-dev",
	"payments": "0.0.1",
	"posawesome": "6.3.0"
}
```
### Route
```
Form/Sales Invoice/new-sales-invoice-hsbycannvs
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1718, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    hooks.append(frappe.get_attr(handler))
  File "apps/frappe/frappe/__init__.py", line 1708, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1429, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/posawesome/posawesome/posawesome/api/invoice.py", line 12, in <module>
    from posawesome.posawesome.api.posapp import get_company_domain
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 15, in <module>
    from erpnext.stock.doctype.batch.batch import (
ImportError: cannot import name 'set_batch_nos' from 'erpnext.stock.doctype.batch.batch' (apps/erpnext/erpnext/stock/doctype/batch/batch.py)

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Sales Invoice\",\"name\":\"new-sales-invoice-dspxvhlxaf\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"william.price@multi-doc.ca\",\"naming_series\":\"ACC-SINV-.YYYY.-\",\"company\":\"Multi-Doc\",\"posting_date\":\"2024-04-19\",\"set_posting_time\":0,\"is_pos\":0,\"is_consolidated\":0,\"is_return\":0,\"update_outstanding_for_self\":1,\"update_billed_amount_in_sales_order\":0,\"update_billed_amount_in_delivery_note\":1,\"is_debit_note\":0,\"currency\":\"CAD\",\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"CAD\",\"ignore_pricing_rule\":0,\"update_stock\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Sales Invoice Item\",\"name\":\"new-sales-invoice-item-likdieihiu\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"william.price@multi-doc.ca\",\"has_item_scanned\":0,\"stock_uom\":\"page\",\"margin_type\":\"\",\"is_free_item\":0,\"grant_commission\":1,\"delivered_by_supplier\":0,\"is_fixed_asset\":0,\"enable_deferred_revenue\":0,\"use_serial_batch_fields\":0,\"allow_zero_valuation_rate\":0,\"cost_center\":\"Main - M\",\"page_break\":0,\"parent\":\"new-sales-invoice-dspxvhlxaf\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"idx\":1,\"qty\":17,\"conversion_factor\":1,\"stock_qty\":17,\"price_list_rate\":0.17,\"base_price_list_rate\":0.17,\"margin_rate_or_amount\":0,\"rate_with_margin\":0.17,\"discount_amount\":0,\"base_rate_with_margin\":0.17,\"rate\":0.17,\"amount\":2.89,\"base_rate\":0.17,\"base_amount\":2.89,\"stock_uom_rate\":0.17,\"net_rate\":0.17,\"net_amount\":2.89,\"base_net_rate\":0.17,\"base_net_amount\":2.89,\"weight_per_unit\":0,\"total_weight\":0,\"incoming_rate\":0,\"actual_batch_qty\":0,\"actual_qty\":0,\"delivered_qty\":0,\"item_code\":\"LTR-20lb-1s-BW\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"LTR-20lb-1s-BW\",\"description\":\"LTR-20lb-1s-BW\",\"image\":\"\",\"warehouse\":\"Stores - M\",\"income_account\":\"Ventes - M\",\"expense_account\":\"Achats de matériel direct - M\",\"discount_account\":null,\"provisional_expense_account\":null,\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"page\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"update_stock\":0,\"last_purchase_rate\":0,\"transaction_date\":\"2024-04-19\",\"against_blanket_order\":null,\"bom_no\":null,\"item_group\":\"Copy Center\",\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"customer_item_code\":null,\"projected_qty\":0,\"reserved_qty\":0,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-sales-invoice-item-likdieihiu\"}],\"taxes\":[{\"docstatus\":0,\"doctype\":\"Sales Taxes and Charges\",\"name\":\"new-sales-taxes-and-charges-psjualhuje\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"william.price@multi-doc.ca\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"cost_center\":\"Main - M\",\"account_currency\":\"CAD\",\"dont_recompute_tax\":0,\"parent\":\"new-sales-invoice-dspxvhlxaf\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"idx\":1,\"row_id\":null,\"account_head\":\"TPS à recevoir - M\",\"description\":\"TPS à recevoir\",\"rate\":5,\"tax_amount\":0.14,\"total\":3.03,\"tax_amount_after_discount_amount\":0.14,\"base_tax_amount\":0.14,\"base_total\":3.03,\"base_tax_amount_after_discount_amount\":0.14,\"item_wise_tax_detail\":\"{\\\"LTR-20lb-1s-BW\\\":[5,0.14]}\"},{\"docstatus\":0,\"doctype\":\"Sales Taxes and Charges\",\"name\":\"new-sales-taxes-and-charges-qdzekbakhx\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"william.price@multi-doc.ca\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"cost_center\":\"Main - M\",\"account_currency\":\"CAD\",\"dont_recompute_tax\":0,\"parent\":\"new-sales-invoice-dspxvhlxaf\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"idx\":2,\"row_id\":null,\"account_head\":\"TVP/TVQ à recevoir - M\",\"description\":\"TVP/TVQ à recevoir\",\"rate\":9.975,\"tax_amount\":0.29,\"total\":3.32,\"tax_amount_after_discount_amount\":0.29,\"base_tax_amount\":0.29,\"base_total\":3.32,\"base_tax_amount_after_discount_amount\":0.29,\"item_wise_tax_detail\":\"{\\\"LTR-20lb-1s-BW\\\":[9.975,0.29]}\"}],\"use_company_roundoff_cost_center\":0,\"disable_rounded_total\":1,\"apply_discount_on\":\"Grand Total\",\"is_cash_or_non_trade_discount\":0,\"pricing_rules\":[],\"posa_offers\":[],\"posa_coupons\":[],\"packed_items\":[],\"timesheets\":[],\"total_billing_amount\":0,\"payments\":[],\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"advances\":[],\"write_off_outstanding_amount_automatically\":0,\"redeem_loyalty_points\":0,\"territory\":\"Canada\",\"ignore_default_payment_terms_template\":0,\"payment_schedule\":[{\"docstatus\":0,\"doctype\":\"Payment Schedule\",\"name\":\"new-payment-schedule-oqosrwixfq\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"william.price@multi-doc.ca\",\"discount_type\":\"Percentage\",\"discounted_amount\":0,\"parent\":\"new-sales-invoice-dspxvhlxaf\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Sales Invoice\",\"idx\":1,\"payment_term\":\"On Reception\",\"description\":null,\"invoice_portion\":100,\"payment_amount\":0,\"base_payment_amount\":0,\"discount\":0,\"outstanding\":0,\"mode_of_payment\":null,\"due_date\":\"2024-04-19\",\"discount_date\":\"2024-04-19\"}],\"party_account_currency\":\"CAD\",\"is_opening\":\"No\",\"sales_team\":[],\"letter_head\":\"None\",\"group_same_items\":0,\"status\":\"Draft\",\"customer_group\":\"Individual\",\"is_internal_customer\":0,\"is_discounted\":0,\"repost_required\":0,\"posting_time\":\"09:05:35\",\"company_tax_id\":\"728551128RT0001\",\"company_address\":\"Defaut-Billing\",\"plc_conversion_rate\":1,\"conversion_rate\":1,\"total_billing_hours\":0,\"company_address_display\":\"2399 Av Jeanne-d`arc<br>Montreal<br>\\nQC<br>H1W 3V8<br>Canada<br>\\nPhone: 5143738289<br>Email: info@multi-doc.ca<br>\",\"tc_name\":\"On Reception\",\"terms\":\"<div class=\\\"ql-editor read-mode\\\"><p>Payable sur reception </p></div>\",\"taxes_and_charges\":\"GST-QST - M\",\"base_net_total\":2.89,\"net_total\":2.89,\"base_total\":2.89,\"total\":2.89,\"total_qty\":17,\"rounding_adjustment\":0,\"grand_total\":3.32,\"base_grand_total\":3.32,\"total_taxes_and_charges\":0.43,\"base_total_taxes_and_charges\":0.43,\"base_rounding_adjustment\":0,\"rounded_total\":0,\"base_rounded_total\":0,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"total_advance\":0,\"write_off_amount\":0,\"paid_amount\":0,\"base_paid_amount\":0,\"change_amount\":0,\"base_change_amount\":0,\"outstanding_amount\":3.32,\"amount_eligible_for_commission\":2.89,\"total_commission\":0.2,\"tax_id\":null,\"customer_name\":\"Cash Sales\",\"loyalty_program\":\"Default\",\"represents_company\":null,\"customer\":\"Cash Sales\",\"debit_to\":\"Comptes clients - M\",\"due_date\":\"2024-04-19\",\"customer_address\":\"Cash Sales-Billing\",\"address_display\":\"2399 Ave Jeanne-D'arc<br>Montreal<br>\\nQc<br>H1W 3V8<br>Canada<br>\\n\",\"shipping_address_name\":null,\"posa_delivery_charges\":null,\"shipping_address\":null,\"tax_category\":\"Selling\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"language\":\"fr-CA\",\"sales_partner\":\"William Price\",\"commission_rate\":7,\"payment_terms_template\":\"On Receipt\",\"cost_center\":\"Main - M\",\"total_net_weight\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery37000532132201374406751": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 32842,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ImportError: cannot import name 'set_batch_nos' from 'erpnext.stock.doctype.batch.batch' (apps/erpnext/erpnext/stock/doctype/batch/batch.py)",
	"exc_type": "ImportError",
	"_exc_source": "posawesome (app)"
}
```
```

### Steps to reproduce

4. See the error

### What is Expected?
to save an invoice

### Screenshots
If applicable, could you add screenshots to help explain your problem?

**Comment by yrestom** [comment]
Now version 15 is available on Frappe Cloud from Custom Bench

**Comment by thida-bcn** [comment]
> Now version 15 is available on Frappe Cloud from Custom Bench

hello sir,
how can we upgrade for self hosted?

**Comment by gitstephanferriggi** [comment]
Go on frappecloud.com, register, create a custom bench and site,  install the applications needed inc. any custom apps via GitHub, import your current backup and you have a cloud hosted version 15 of ErpNext Including POS Awesome V15.
