### ISSUE TITLE
[BUG]: POSA v14 not installing on current version of Frappe 14.76.2

### ISSUE THREAD

**Issue by karanwilson** [yrestom/POS-Awesome#475]
### Versions

ERPNext: v14.70.6 (version-14)
Frappe Framework: v14.76.2 (version-14)
Payments: v0.0.1 (develop)

### Stacktrace / full error message

```javascript
bench get-app https://github.com/yrestom/POS-Awesome.git
Getting POS-Awesome
$ git clone https://github.com/yrestom/POS-Awesome.git  --depth 1 --origin upstream
Cloning into 'POS-Awesome'...
remote: Enumerating objects: 209, done.
remote: Counting objects: 100% (209/209), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 209 (delta 38), reused 123 (delta 23), pack-reused 0
Receiving objects: 100% (209/209), 2.25 MiB | 3.21 MiB/s, done.
Resolving deltas: 100% (38/38), done.
Ignoring dependencies of https://github.com/yrestom/POS-Awesome.git. To install dependencies use --resolve-deps
Installing posawesome
$ /home/erpnext/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/erpnext/frappe-bench/apps/posawesome 
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/erpnext/frappe-bench/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/erpnext/frappe-bench/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/erpnext/frappe-bench/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-45cys65j/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-45cys65j/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-45cys65j/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-45cys65j/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-45cys65j/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "/home/erpnext/frappe-bench/apps/posawesome/posawesome/__init__.py", line 3, in <module>
          import frappe
      ModuleNotFoundError: No module named 'frappe'
      [end of output]
```

### Steps to reproduce

1. Install current Frappe 14.76.2
2. bench get-app https://github.com/yrestom/POS-Awesome.git
3. See the error

### What is Expected?
Should install successfully

### What is actually happening?
ModuleNotFoundError: No module named 'frappe'

**Comment by karanwilson** [comment]
Dear @yrestom, would you be releasing later versions of POSA in this github repo?

**Comment by yrestom** [comment]
Install it using `bench get-app branch version-14 https://github.com/yrestom/POS-Awesome.git`

**Comment by karanwilson** [comment]
Hi @yrestom, I had tried installing version-14 first;
Here are the full logs:-

bench get-app branch version-14 https://github.com/yrestom/POS-Awesome.git
Getting POS-Awesome
$ git clone https://github.com/yrestom/POS-Awesome.git  --depth 1 --origin upstream
Cloning into 'POS-Awesome'...
remote: Enumerating objects: 209, done.
remote: Counting objects: 100% (209/209), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 209 (delta 38), reused 123 (delta 23), pack-reused 0
Receiving objects: 100% (209/209), 2.25 MiB | 8.26 MiB/s, done.
Resolving deltas: 100% (38/38), done.
Ignoring dependencies of https://github.com/yrestom/POS-Awesome.git. To install dependencies use --resolve-deps
Installing posawesome
$ /home/erpnext/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/erpnext/frappe-bench/apps/posawesome 
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/erpnext/frappe-bench/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/erpnext/frappe-bench/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/erpnext/frappe-bench/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-1yvnw371/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-1yvnw371/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-1yvnw371/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-1yvnw371/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-1yvnw371/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "/home/erpnext/frappe-bench/apps/posawesome/posawesome/__init__.py", line 3, in <module>
          import frappe
      ModuleNotFoundError: No module named 'frappe'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: /home/erpnext/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/erpnext/frappe-bench/apps/posawesome 
subprocess.CalledProcessError: Command '/home/erpnext/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/erpnext/frappe-bench/apps/posawesome ' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 181, in get_app
    get_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 777, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 254, in install
    install_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 909, in install_app
    bench.run(
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/__init__.py", line 178, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: /home/erpnext/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/erpnext/frappe-bench/apps/posawesome

**Comment by karanwilson** [comment]
tried installing in Frappe 14.52.1 and it install just fine.

**Comment by karanwilson** [comment]
thanks @yrestom , the POSA version-14 branch is now installing in the current Frappe version-14
