### ISSUE TITLE
[BUG]: Invalid file path: point-of-sale.bundle.js

### ISSUE THREAD

**Issue by hankjordan** [yrestom/POS-Awesome#69]
### Versions

- Frappe: v13.x.x-develop () (develop)
- Erpnext: v13.x.x-develop () (develop)
- POS Awesome: POS Awesome: v2.0.1 (master)

### Stacktrace / full error message

```python
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/client.py", line 327, in get_js
    frappe.throw(_("Invalid file path: {0}").format("/".join(src)))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 435, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 414, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 368, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Invalid file path: point-of-sale.bundle.js
```

### Steps to reproduce

1. Go to Point of Sale

### What is Expected?

Point of sale opens.

### What is actually happening?

POS fails to open, shows file path invalid error message.
Domain entry for POSAwesome is also missing.

### Additional context

- Running on docker
- Fresh install still has issue
- point-of-sale.bundle.js exists at assets/erpnext/js/point-of-sale.bundle.js

Issue did not exist before POSAwesome was installed. Might just be a configuration problem but I am hoping somebody can point me in the right direction !

**Comment by yrestom** [comment]
I don't think this error has anything to do with POS Awesome because it does not use point-of-sale.js file
If you have any additional information that may help please let me know
